export const questions: Question[] = [
  {
    _id: "1",
    title: "What is TypeScript?",
    body: "Can someone explain what TypeScript is and how it differs from JavaScript?",
    tags: [
      { _id: "1", name: "TypeScript" },
      { _id: "11", name: "JavaScript" },
      { _id: "12", name: "Programming" },
    ],
    author: { _id: "1", name: "John Doe", avatar: "/avator.png", value: 42 },
    createdAt: new Date(),
    upvotes: 10,
    answerscount: 2,
    views: 100,
  },
  {
    _id: "2",
    title: "How to use useState in React?",
    body: "I am new to React and I am having trouble understanding how to use the useState hook.",
    tags: [
      { _id: "2", name: "React" },
      { _id: "13", name: "Hooks" },
      { _id: "14", name: "Frontend" },
    ],
    author: { _id: "2", name: "Jane Smith", avatar: "/avator.png", value: 37 },
    createdAt: new Date(),
    upvotes: 15,
    answerscount: 3,
    views: 150,
  },
  {
    _id: "3",
    title: "What is Node.js?",
    body: "Can someone explain what Node.js is and why it is used?",
    tags: [
      { _id: "3", name: "Nodejs" },
      { _id: "15", name: "Backend" },
      { _id: "16", name: "JavaScript" },
    ],
    author: {
      _id: "3",
      name: "Alice Johnson",
      avatar: "/avator.png",
      value: 29,
    },
    createdAt: new Date(),
    upvotes: 20,
    answerscount: 5,
    views: 200,
  },
  {
    _id: "4",
    title: "How to manage state in Redux?",
    body: "I am having trouble understanding how to manage state in a Redux application.",
    tags: [
      { _id: "4", name: "Redux" },
      { _id: "17", name: "State Management" },
      { _id: "18", name: "React" },
    ],
    author: { _id: "4", name: "Bob Brown", avatar: "/avator.png", value: 33 },
    createdAt: new Date(),
    upvotes: 25,
    answerscount: 4,
    views: 250,
  },
  {
    _id: "5",
    title: "What is MongoDB?",
    body: "Can someone explain what MongoDB is and how it is different from SQL databases?",
    tags: [
      { _id: "5", name: "MongoDB" },
      { _id: "19", name: "Database" },
      { _id: "20", name: "NoSQL" },
    ],
    author: {
      _id: "5",
      name: "Charlie Davis",
      avatar: "/avator.png",
      value: 45,
    },
    createdAt: new Date(),
    upvotes: 30,
    answerscount: 6,
    views: 300,
  },
  {
    _id: "6",
    title: "How to use Express.js?",
    body: "I am new to backend development and I am having trouble understanding how to use Express.js.",
    tags: [
      { _id: "6", name: "Express.js" },
      { _id: "21", name: "Backend" },
      { _id: "22", name: "Nodejs" },
    ],
    author: { _id: "6", name: "David Evans", avatar: "/avator.png", value: 28 },
    createdAt: new Date(),
    upvotes: 35,
    answerscount: 7,
    views: 350,
  },
  {
    _id: "7",
    title: "What is GraphQL?",
    body: "Can someone explain what GraphQL is and how it is different from REST APIs?",
    tags: [
      { _id: "7", name: "GraphQL" },
      { _id: "23", name: "API" },
      { _id: "24", name: "Backend" },
    ],
    author: { _id: "7", name: "Eve Foster", avatar: "/avator.png", value: 39 },
    createdAt: new Date(),
    upvotes: 40,
    answerscount: 8,
    views: 400,
  },
  {
    _id: "8",
    title: "How to use Docker?",
    body: "I am new to DevOps and I am having trouble understanding how to use Docker.",
    tags: [
      { _id: "8", name: "Docker" },
      { _id: "25", name: "DevOps" },
      { _id: "26", name: "Containers" },
    ],
    author: { _id: "8", name: "Frank Green", avatar: "/avator.png", value: 41 },
    createdAt: new Date(),
    upvotes: 45,
    answerscount: 9,
    views: 450,
  },
  {
    _id: "9",
    title: "What is Kubernetes?",
    body: "Can someone explain what Kubernetes is and why it is used?",
    tags: [
      { _id: "9", name: "Kubernetes" },
      { _id: "27", name: "DevOps" },
      { _id: "28", name: "Containers" },
    ],
    author: {
      _id: "9",
      name: "Grace Harris",
      avatar: "/avator.png",
      value: 36,
    },
    createdAt: new Date(),
    upvotes: 50,
    answerscount: 10,
    views: 500,
  },
  {
    _id: "10",
    title: "How to use Next.js?",
    body: "I am new to server-side rendering and I am having trouble understanding how to use Next.js.",
    tags: [
      { _id: "10", name: "Nextjs" },
      { _id: "29", name: "React" },
      { _id: "30", name: "SSR" },
    ],
    author: {
      _id: "10",
      name: "Henry Irving",
      avatar: "/avator.png",
      value: 34,
    },
    createdAt: new Date(),
    upvotes: 55,
    answerscount: 11,
    views: 550,
  },
];
